package net.seniorsteps.senior.vetclinic.dal.entity;
// Generated Jul 16, 2020 5:35:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DoctorEntity generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="vet_clinic"
    , uniqueConstraints = @UniqueConstraint(columnNames="phone") 
)
public class DoctorEntity  implements java.io.Serializable {


     private Integer idr;
     private ClinicEntity clinic;
     private String name;
     private String phone;
     private String photoPath;
     private String bioPath;
     private Set<VisitEntity> visits = new HashSet<VisitEntity>(0);

    public DoctorEntity() {
    }

	
    public DoctorEntity(ClinicEntity clinic, String name, String phone) {
        this.clinic = clinic;
        this.name = name;
        this.phone = phone;
    }
    public DoctorEntity(ClinicEntity clinic, String name, String phone, String photoPath, String bioPath, Set<VisitEntity> visits) {
       this.clinic = clinic;
       this.name = name;
       this.phone = phone;
       this.photoPath = photoPath;
       this.bioPath = bioPath;
       this.visits = visits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idr", unique=true, nullable=false)
    public Integer getIdr() {
        return this.idr;
    }
    
    public void setIdr(Integer idr) {
        this.idr = idr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Clinic_id", nullable=false)
    public ClinicEntity getClinic() {
        return this.clinic;
    }
    
    public void setClinic(ClinicEntity clinic) {
        this.clinic = clinic;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="photo_path")
    public String getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    
    @Column(name="bio_path")
    public String getBioPath() {
        return this.bioPath;
    }
    
    public void setBioPath(String bioPath) {
        this.bioPath = bioPath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<VisitEntity> getVisits() {
        return this.visits;
    }
    
    public void setVisits(Set<VisitEntity> visits) {
        this.visits = visits;
    }




}


