package net.seniorsteps.senior.vetclinic.dal.entity;
// Generated Jul 16, 2020 5:35:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OwnerEntity generated by hbm2java
 */
@Entity
@Table(name="owner"
    ,catalog="vet_clinic"
    , uniqueConstraints = {@UniqueConstraint(columnNames="phone"), @UniqueConstraint(columnNames="email")} 
)
public class OwnerEntity  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String phone;
     private String gender;
     private String address;
     private Set<PetEntity> pets = new HashSet<PetEntity>(0);

    public OwnerEntity() {
    }

	
    public OwnerEntity(String name, String email, String phone, String gender, String address) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.gender = gender;
        this.address = address;
    }
    public OwnerEntity(String name, String email, String phone, String gender, String address, Set<PetEntity> pets) {
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.gender = gender;
       this.address = address;
       this.pets = pets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="gender", nullable=false, length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<PetEntity> getPets() {
        return this.pets;
    }
    
    public void setPets(Set<PetEntity> pets) {
        this.pets = pets;
    }




}


