package net.seniorsteps.senior.vetclinic.dal.entity;
// Generated Jul 16, 2020 5:35:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PetEntity generated by hbm2java
 */
@Entity
@Table(name="pet"
    ,catalog="vet_clinic"
)
public class PetEntity  implements java.io.Serializable {


     private Integer id;
     private OwnerEntity owner;
     private String name;
     private String gender;
     private Date dateOfBirth;
     private String animalKind;
     private String photoPath;
     private float weight;
     private Set<VisitEntity> visits = new HashSet<VisitEntity>(0);

    public PetEntity() {
    }

	
    public PetEntity(OwnerEntity owner, String name, String gender, Date dateOfBirth, String animalKind, String photoPath, float weight) {
        this.owner = owner;
        this.name = name;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.animalKind = animalKind;
        this.photoPath = photoPath;
        this.weight = weight;
    }
    public PetEntity(OwnerEntity owner, String name, String gender, Date dateOfBirth, String animalKind, String photoPath, float weight, Set<VisitEntity> visits) {
       this.owner = owner;
       this.name = name;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.animalKind = animalKind;
       this.photoPath = photoPath;
       this.weight = weight;
       this.visits = visits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Owner_id", nullable=false)
    public OwnerEntity getOwner() {
        return this.owner;
    }
    
    public void setOwner(OwnerEntity owner) {
        this.owner = owner;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="gender", nullable=false, length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="animal_kind", nullable=false, length=45)
    public String getAnimalKind() {
        return this.animalKind;
    }
    
    public void setAnimalKind(String animalKind) {
        this.animalKind = animalKind;
    }

    
    @Column(name="photo_path", nullable=false, length=150)
    public String getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    
    @Column(name="weight", nullable=false, precision=12, scale=0)
    public float getWeight() {
        return this.weight;
    }
    
    public void setWeight(float weight) {
        this.weight = weight;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pet")
    public Set<VisitEntity> getVisits() {
        return this.visits;
    }
    
    public void setVisits(Set<VisitEntity> visits) {
        this.visits = visits;
    }




}


