package net.seniorsteps.senior.vetclinic.dal.entity;
// Generated Jul 16, 2020 5:35:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisitEntity generated by hbm2java
 */
@Entity
@Table(name="visit"
    ,catalog="vet_clinic"
)
public class VisitEntity  implements java.io.Serializable {


     private Integer id;
     private ClinicEntity clinic;
     private DoctorEntity doctor;
     private PetEntity pet;
     private Date date;

    public VisitEntity() {
    }

    public VisitEntity(ClinicEntity clinic, DoctorEntity doctor, PetEntity pet, Date date) {
       this.clinic = clinic;
       this.doctor = doctor;
       this.pet = pet;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Clinic_id", nullable=false)
    public ClinicEntity getClinic() {
        return this.clinic;
    }
    
    public void setClinic(ClinicEntity clinic) {
        this.clinic = clinic;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Doctor_idr", nullable=false)
    public DoctorEntity getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(DoctorEntity doctor) {
        this.doctor = doctor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pet_id", nullable=false)
    public PetEntity getPet() {
        return this.pet;
    }
    
    public void setPet(PetEntity pet) {
        this.pet = pet;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


